### ISSUE TITLE
Unable to install bignum

### ISSUE THREAD

**Issue by varungupta2015135** [justmoon/node-bignum#113]
When I type in: npm install --save bignum
It gives me this error:

> bignum@0.13.0 install D:\torrent-client\node_modules\bignum
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=8.11.1 runtime=node arch=x64 platform=win32)

D:\torrent-client\node_modules\bignum>if not defined npm_config_node_gyp (node "C:\Users\tak1za\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\tak1za\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\ProgramData\Anaconda3\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\tak1za\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\tak1za\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at C:\Users\tak1za\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\tak1za\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\torrent-client\node_modules\bignum
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm WARN torrent-client@1.0.0 No description
npm WARN torrent-client@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bignum@0.13.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bignum@0.13.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tak1za\AppData\Roaming\npm-cache\_logs\2018-07-21T14_41_19_467Z-debug.log

**Comment by upupming** [comment]
I got this error too

**Comment by varungupta2015135** [comment]
I was able to solve it by using Python 2.7 instead of 3.x
Hope it helps!
And do revert if you are able to solve it too by doing what I mentioned above so I can close this issue

**Comment by upupming** [comment]
thanks!
