### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by OlMi1** [justmoon/node-bignum#132]
(I hope I'm in the right repo here :x)
Log:
```
make: *** [bignum.target.mk:105: Release/obj.target/bignum/bignum.o] Error 1
make: Leaving directory '/home/pool/pool/node_modules/bignum/build'
gyp ERR! build error
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/nodejs/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.0
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "build" "--fallback-to-build" "--module=/home/pool/pool/node_modules/bignum/binding/bignum.node" "--module_name=bignum" "--module_path=/home/pool/pool/node_modules/bignum/binding"
gyp ERR! cwd /home/pool/pool/node_modules/bignum
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/bin/node-gyp build --fallback-to-build --module=/home/pool/pool/node_modules/bignum/binding/bignum.node --module_name=bignum --module_path=/home/pool/pool/node_modules/bignum/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pool/pool/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 5.4.0
node-pre-gyp ERR! command "/usr/bin/node" "/home/pool/pool/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pool/pool/node_modules/bignum
node-pre-gyp ERR! node -v v10.19.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/bin/node-gyp build --fallback-to-build --module=/home/pool/pool/node_modules/bignum/binding/bignum.node --module_name=bignum --module_path=/home/pool/pool/node_modules/bignum/binding' (1)
make: *** [bignum.target.mk:105: Release/obj.target/bignum/bignum.o] Error 1
make: Leaving directory '/home/pool/pool/node_modules/bignum/build'
gyp ERR! build error
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/nodejs/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.0
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "build" "--fallback-to-build" "--module=/home/pool/pool/node_modules/bignum/binding/bignum.node" "--module_name=bignum" "--module_path=/home/pool/pool/node_modules/bignum/binding"
gyp ERR! cwd /home/pool/pool/node_modules/bignum
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bignum@0.12.5 install: node-pre-gyp install --fallback-to-build
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bignum@0.12.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-25T14_34_46_730Z-debug.log
```
What should I do?

**Comment by OlMi1** [comment]
I was able to move away from bignum.
