### ISSUE TITLE
build failure:  fatal error: 'v8.h' file not found

### ISSUE THREAD

**Issue by yi** [justmoon/node-bignum#26]
```
npm http 304 https://registry.npmjs.org/bignum

> bignum@0.6.2 install /Users/sgfdeployer/temp/node_modules/mongoose-shortid/node_modules/bignum
> node-gyp configure build

  CXX(target) Release/obj.target/bignum/bignum.o
../bignum.cc:8:10: fatal error: 'v8.h' file not found
#include <v8.h>
         ^
1 error generated.
make: *** [Release/obj.target/bignum/bignum.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:236:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Darwin 13.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/sgfdeployer/temp/node_modules/mongoose-shortid/node_modules/bignum
gyp ERR! node -v v0.8.14
gyp ERR! node-gyp -v v0.7.1
gyp ERR! not ok 
npm ERR! bignum@0.6.2 install: `node-gyp configure build`
npm ERR! `sh "-c" "node-gyp configure build"` failed with 1
npm ERR! 
npm ERR! Failed at the bignum@0.6.2 install script.
npm ERR! This is most likely a problem with the bignum package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls bignum
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "."
npm ERR! cwd /Users/sgfdeployer/temp
npm ERR! node -v v0.8.14
npm ERR! npm -v 1.1.65
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/sgfdeployer/temp/npm-debug.log
npm ERR! not ok code 0

```

**Comment by rvagg** [comment]
closing cause old .. please reopen if you still have a problem
