### ISSUE TITLE
node-gyp bulid failure

### ISSUE THREAD

**Issue by abbshr** [justmoon/node-bignum#29]
`sudo npm install bignum`

then I got this log

```
    npm http GET https://registry.npmjs.org/bignum
    npm http 304 https://registry.npmjs.org/bignum

    > bignum@0.6.2 install /home/ran/external/insight-api/node_modules/bignum
    > node-gyp configure build

    gyp: /home/ran/.node-gyp/0.10.25/common.gypi not found (cwd: /home/ran/external/insight-api/node_modules/bignum) while reading includes of binding.gyp
    gyp ERR! configure error 
    gyp ERR! stack Error: `gyp` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:337:16)
    gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
    gyp ERR! System Linux 3.2.0-29-generic
    gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
    gyp ERR! cwd /home/ran/external/insight-api/node_modules/bignum
    gyp ERR! node -v v0.10.25
    gyp ERR! node-gyp -v v0.12.2
    gyp ERR! not ok 
    npm ERR! bignum@0.6.2 install: `node-gyp configure build`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the bignum@0.6.2 install script.
    npm ERR! This is most likely a problem with the bignum package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp configure build
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls bignum
    npm ERR! There is likely additional logging output above.

    npm ERR! System Linux 3.2.0-29-generic
    npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "bignum"
    npm ERR! cwd /home/ran/external/insight-api
    npm ERR! node -v v0.10.25
    npm ERR! npm -v 1.3.24
    npm ERR! code ELIFECYCLE
    npm ERR! 
    npm ERR! Additional logging details can be found in:
    npm ERR!     /home/ran/external/insight-api/npm-debug.log
    npm ERR! not ok code 0
```

anyone have solution?

**Comment by edimoldovan** [comment]
I am having the exact same issue on OS X with latest node (0.12.0). How did you fix it?

**Comment by cyberwombat** [comment]
It appears that the error stems from modules with outdated bigness dependencies. I ran into a bunch of these errors doing `npm update`. You can find the guilty modules with `find node_modules -iname 'package.json' -exec grep -r 'bignum' {} \;` then either upgrade their version if you can or delete/forknfix. I ran [depcheck](https://www.npmjs.com/package/depcheck) and realized I didn't need many of these.
