### ISSUE TITLE
possible iojs issue

### ISSUE THREAD

**Issue by xjamundx** [justmoon/node-bignum#36]
I'm seeing the following:

```
~/dev/testbig $ iojs
> require('bignum')
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:341:32)
    at Function.Module._load (module.js:296:12)
    at Module.require (module.js:351:17)
    at new require (module.js:370:17)
    at Object.<anonymous> (/Users/jamuferguson/dev/testbig/node_modules/bignum/index.js:4:14)
    at Module._compile (module.js:446:26)
    at Object.Module._extensions..js (module.js:464:10)
    at Module.load (module.js:341:32)
    at Function.Module._load (module.js:296:12)
```

Here is what the install looks like:
```
~/dev/testbig $ npm install bignum
npm WARN package.json testbig@1.0.0 No description
npm WARN package.json testbig@1.0.0 No repository field.
npm WARN package.json testbig@1.0.0 No README data
-
> bignum@0.9.1 install /Users/jamuferguson/dev/testbig/node_modules/bignum
> node-gyp configure build

  CXX(target) Release/obj.target/bignum/bignum.o
  SOLINK_MODULE(target) Release/bignum.node
  SOLINK_MODULE(target) Release/bignum.node: Finished
bignum@0.9.1 node_modules/bignum
└── nan@1.5.3
```

**Comment by xjamundx** [comment]
Answer: USE THE RIGHT VERSION OF NPM THAT GETS INSTALLED WITH IOJS
