### ISSUE TITLE
lots of issues with v0.11 and v0.12

### ISSUE THREAD

**Issue by tobsn** [justmoon/node-bignum#43]
lots of compile errors:
```
child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/bignum/bignum.o
../bignum.cc:172:16: error: expected class name
class BigNum : ObjectWrap {
               ^
../bignum.cc:189:34: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> New(const Arguments& args);
                                 ^~~~~~~~~
                                 v8::internal::Arguments
/Users/tobias/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:190:39: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> ToString(const Arguments& args);
                                      ^~~~~~~~~
                                      v8::internal::Arguments
/Users/tobias/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:191:35: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> Badd(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/tobias/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:192:35: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> Bsub(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/tobias/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:193:35: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> Bmul(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/tobias/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:194:35: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> Bdiv(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/tobias/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:195:35: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> Uadd(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/tobias/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:196:35: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> Usub(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/tobias/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:197:35: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> Umul(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/tobias/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:198:35: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> Udiv(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/tobias/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:199:40: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> Umul_2exp(const Arguments& args);
                                       ^~~~~~~~~
                                       v8::internal::Arguments
/Users/tobias/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:200:40: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> Udiv_2exp(const Arguments& args);
                                       ^~~~~~~~~
                                       v8::internal::Arguments
/Users/tobias/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:201:35: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> Babs(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/tobias/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:202:35: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> Bneg(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/tobias/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:203:35: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> Bmod(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/tobias/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:204:35: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> Umod(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/tobias/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:205:36: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> Bpowm(const Arguments& args);
                                   ^~~~~~~~~
                                   v8::internal::Arguments
/Users/tobias/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:206:36: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> Upowm(const Arguments& args);
                                   ^~~~~~~~~
                                   v8::internal::Arguments
/Users/tobias/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/bignum/bignum.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/tobias/.nodebrew/node/v0.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/Users/tobias/.nodebrew/node/v0.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/tobias/Projects/app/node_modules/ip2loc/node_modules/bignum
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
```

**Comment by rvagg** [comment]
you need to get ip2loc to update its dependency on bignum, it's kind of old which is why this is breaking: https://github.com/stanislaw-glogowski/node-ip2loc/blob/master/package.json#L25
