### ISSUE TITLE
node-gyp configure build fails on Mac OS 10.10

### ISSUE THREAD

**Issue by AndyBarron** [justmoon/node-bignum#45]
# System information
* OS: Mac OS 10.10.2
* Compiler: Apple LLVM version 6.1.0 (clang-602.0.49)
* Node version: 0.12.2
* NPM version: 2.7.4

# Errors
```
> node-gyp configure build

  CXX(target) Release/obj.target/bignum/bignum.o
../bignum.cc:172:16: error: expected class name
class BigNum : ObjectWrap {
               ^
../bignum.cc:189:34: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> New(const Arguments& args);
                                 ^~~~~~~~~
                                 v8::internal::Arguments
/Users/andy/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:190:39: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> ToString(const Arguments& args);
                                      ^~~~~~~~~
                                      v8::internal::Arguments
/Users/andy/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:191:35: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Badd(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/andy/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:192:35: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Bsub(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/andy/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:193:35: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Bmul(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/andy/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:194:35: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Bdiv(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/andy/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:195:35: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Uadd(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/andy/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:196:35: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Usub(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/andy/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:197:35: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Umul(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/andy/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:198:35: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Udiv(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/andy/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:199:40: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Umul_2exp(const Arguments& args);
                                       ^~~~~~~~~
                                       v8::internal::Arguments
/Users/andy/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:200:40: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Udiv_2exp(const Arguments& args);
                                       ^~~~~~~~~
                                       v8::internal::Arguments
/Users/andy/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:201:35: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Babs(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/andy/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:202:35: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Bneg(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/andy/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:203:35: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Bmod(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/andy/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:204:35: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Umod(const Arguments& args);
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/andy/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:205:36: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Bpowm(const Arguments& args);
                                   ^~~~~~~~~
                                   v8::internal::Arguments
/Users/andy/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../bignum.cc:206:36: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Upowm(const Arguments& args);
                                   ^~~~~~~~~
                                   v8::internal::Arguments
/Users/andy/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/bignum/bignum.o] Error 1
ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/andy/projects/resume/site/node_modules/mongoose-shortid/node_modules/bignum
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 

[. . . other modules install . . .]

npm ERR! Darwin 14.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! bignum@0.6.2 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bignum@0.6.2 install script 'node-gyp configure build'.
npm ERR! This is most likely a problem with the bignum package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls bignum
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/andy/projects/resume/site/npm-debug.log
```

**Comment by AndyBarron** [comment]
False alarm, turns out mongoose-shortid depends on an outdated version of this module. Sorry!!!
