### ISSUE TITLE
The specified module could not be found.

### ISSUE THREAD

**Issue by SVasilev** [justmoon/node-bignum#50]
Hey there,
I use nodejs x64 on Windows 7. I've already installed Win64OpenSSL-1_0_0r. I ran "npm install -g bignum" and it didn't fail. Now, the problem is when i try to use the module in a simple hello world application it fails. In a file called server.js i have this line:

var BigNum = require('bignum');

C:\Users\Sopata\bigINt>node server.js
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: The specified module could not be found.
C:\Users\Sopata\node_modules\bignum\build\Release\bignum.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at new require (module.js:384:17)
    at Object.<anonymous> (C:\Users\i312038\node_modules\bignum\index.js:4:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

I am pretty new to nodejs so this could not be a problem with the module but with my machine.

**Comment by dirkbonhomme** [comment]
You've installed bignum as a global CLI tool with the "-g" option. Can you try to do "npm install bignum"? This will install is locally in the "node_modules" folder.

**Comment by SVasilev** [comment]
Thanks for the feedback. I solved the problem. I ran "npm install bignum" but for some reason it didn't installed it locally. So i had to manually crate node_modules folder and copy the bignum module from the global node_modules folder in my local one. So yes, it's basically an issue with my OS or somewhat. Sorry for the somewhat irrelevant issue i posted. This can be closed.
