### ISSUE TITLE
npm install fails on FreeBSD 10.0-RELEASE-p7

### ISSUE THREAD

**Issue by benneumob** [justmoon/node-bignum#56]
## Stack
gyp ERR! build error 
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System FreeBSD 10.0-RELEASE-p7
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /usr/home/nmadmin/node_modules/bignum
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! FreeBSD 10.0-RELEASE-p7
npm ERR! argv "node" "/usr/local/bin/npm" "install" "bignum@latest"
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE

npm ERR! bignum@0.10.2 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bignum@0.10.2 install script 'node-gyp configure build'.
npm ERR! This is most likely a problem with the bignum package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls bignum
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/home/nmadmin/npm-debug.log

## Full Log:

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', 'bignum@latest' ]
2 info using npm@2.12.1
3 info using node@v0.12.7
4 verbose install initial load of /usr/home/nmadmin/package.json
5 verbose installManyTop reading scoped package data from /usr/home/nmadmin/node_modules/async/package.json
6 verbose readDependencies loading dependencies from /usr/home/nmadmin/package.json
7 silly cache add args [ 'bignum@latest', null ]
8 verbose cache add spec bignum@latest
9 silly cache add parsed spec { raw: 'bignum@latest',
9 silly cache add   scope: null,
9 silly cache add   name: 'bignum',
9 silly cache add   rawSpec: 'latest',
9 silly cache add   spec: 'latest',
9 silly cache add   type: 'tag' }
10 silly addNamed bignum@latest
11 verbose addNamed "latest" is being treated as a dist-tag for bignum
12 info addNameTag [ 'bignum', 'latest' ]
13 silly mapToRegistry name bignum
14 silly mapToRegistry using default registry
15 silly mapToRegistry registry https://registry.npmjs.org/
16 silly mapToRegistry uri https://registry.npmjs.org/bignum
17 verbose addNameTag registry:https://registry.npmjs.org/bignum not in flight; fetching
18 verbose request uri https://registry.npmjs.org/bignum
19 verbose request no auth needed
20 info attempt registry request try #1 at 18:07:56
21 verbose request id 03be6f877b447e75
22 verbose etag "CLBTQMP4PRNXCDNUOP74PQZU8"
23 http request GET https://registry.npmjs.org/bignum
24 http 304 https://registry.npmjs.org/bignum
25 silly get cb [ 304,
25 silly get   { date: 'Mon, 20 Jul 2015 18:09:10 GMT',
25 silly get     via: '1.1 varnish',
25 silly get     'cache-control': 'max-age=60',
25 silly get     etag: '"CLBTQMP4PRNXCDNUOP74PQZU8"',
25 silly get     age: '0',
25 silly get     connection: 'keep-alive',
25 silly get     'x-served-by': 'cache-dfw1830-DFW',
25 silly get     'x-cache': 'HIT',
25 silly get     'x-cache-hits': '1',
25 silly get     'x-timer': 'S1437415750.409926,VS0,VE49',
25 silly get     vary: 'Accept' } ]
26 verbose etag https://registry.npmjs.org/bignum from cache
27 verbose get saving bignum to /home/nmadmin/.npm/registry.npmjs.org/bignum/.cache.json
28 silly addNameTag next cb for bignum with tag latest
29 silly addNamed bignum@0.10.2
30 verbose addNamed "0.10.2" is a plain semver version for bignum
31 silly cache afterAdd bignum@0.10.2
32 verbose afterAdd /home/nmadmin/.npm/bignum/0.10.2/package/package.json not in flight; writing
33 verbose afterAdd /home/nmadmin/.npm/bignum/0.10.2/package/package.json written
34 silly install resolved [ { name: 'bignum',
34 silly install resolved     version: '0.10.2',
34 silly install resolved     description: 'Arbitrary-precision integer arithmetic using OpenSSL',
34 silly install resolved     main: './index.js',
34 silly install resolved     repository:
34 silly install resolved      { type: 'git',
34 silly install resolved        url: 'git+ssh://git@github.com/justmoon/node-bignum.git' },
34 silly install resolved     keywords:
34 silly install resolved      [ 'openssl',
34 silly install resolved        'big',
34 silly install resolved        'bignum',
34 silly install resolved        'bigint',
34 silly install resolved        'integer',
34 silly install resolved        'arithmetic',
34 silly install resolved        'precision' ],
34 silly install resolved     author:
34 silly install resolved      { name: 'Stefan Thomas',
34 silly install resolved        email: 'justmoon@members.fsf.org',
34 silly install resolved        url: 'http://www.justmoon.net' },
34 silly install resolved     dependencies: { nan: '~1.8.4' },
34 silly install resolved     devDependencies: { expresso: '>=0.6.0', binary: '>=0.1.7', put: '>=0.0.5' },
34 silly install resolved     license: 'MIT/X11',
34 silly install resolved     engine: { node: '>=0.8.0' },
34 silly install resolved     scripts: { install: 'node-gyp configure build', test: 'expresso' },
34 silly install resolved     contributors: [ [Object] ],
34 silly install resolved     gitHead: 'df9114cb731c9eabe9fcdd655949f70e6d530448',
34 silly install resolved     bugs: { url: 'https://github.com/justmoon/node-bignum/issues' },
34 silly install resolved     homepage: 'https://github.com/justmoon/node-bignum#readme',
34 silly install resolved     _id: 'bignum@0.10.2',
34 silly install resolved     _shasum: '85e3bfaec4024960a23e2d2be118b6f459d43af7',
34 silly install resolved     _from: 'bignum@latest',
34 silly install resolved     _npmVersion: '2.11.3',
34 silly install resolved     _nodeVersion: '2.3.1',
34 silly install resolved     _npmUser: { name: 'rvagg', email: 'rod@vagg.org' },
34 silly install resolved     maintainers: [ [Object], [Object], [Object] ],
34 silly install resolved     dist:
34 silly install resolved      { shasum: '85e3bfaec4024960a23e2d2be118b6f459d43af7',
34 silly install resolved        tarball: 'http://registry.npmjs.org/bignum/-/bignum-0.10.2.tgz' },
34 silly install resolved     directories: {},
34 silly install resolved     _resolved: 'https://registry.npmjs.org/bignum/-/bignum-0.10.2.tgz',
34 silly install resolved     readme: 'ERROR: No README data found!' } ]
35 info install bignum@0.10.2 into /usr/home/nmadmin
36 info installOne bignum@0.10.2
37 verbose installOne of bignum to /usr/home/nmadmin not in flight; installing
38 verbose lock using /home/nmadmin/.npm/_locks/bignum-c76c7b87b91b2968.lock for /usr/home/nmadmin/node_modules/bignum
39 silly install write writing bignum 0.10.2 to /usr/home/nmadmin/node_modules/bignum
40 verbose unbuild node_modules/bignum
41 silly gentlyRm /usr/home/nmadmin/node_modules/bignum is being purged from base /usr/home/nmadmin
42 verbose gentlyRm don't care about contents; nuking /usr/home/nmadmin/node_modules/bignum
43 verbose tar unpack /home/nmadmin/.npm/bignum/0.10.2/package.tgz
44 verbose tar unpacking to /usr/home/nmadmin/node_modules/bignum
45 silly gentlyRm /usr/home/nmadmin/node_modules/bignum is being purged
46 verbose gentlyRm don't care about contents; nuking /usr/home/nmadmin/node_modules/bignum
47 silly gunzTarPerm modes [ '755', '644' ]
48 silly gunzTarPerm extractEntry package.json
49 silly gunzTarPerm extractEntry .npmignore
50 silly gunzTarPerm extractEntry index.js
51 silly gunzTarPerm extractEntry binding.gyp
52 silly gunzTarPerm extractEntry README.markdown
53 silly gunzTarPerm extractEntry bignum.cc
54 silly gunzTarPerm modified mode [ 'bignum.cc', 436, 420 ]
55 silly gunzTarPerm extractEntry examples/gen.js
56 silly gunzTarPerm extractEntry examples/perfect.js
57 silly gunzTarPerm extractEntry examples/simple.js
58 silly gunzTarPerm extractEntry .dntrc
59 silly gunzTarPerm extractEntry .travis.yml
60 silly gunzTarPerm extractEntry test/big.js
61 silly gunzTarPerm extractEntry test/buf.js
62 silly gunzTarPerm extractEntry test/gh52.js
63 silly gunzTarPerm modified mode [ 'test/gh52.js', 436, 420 ]
64 silly gunzTarPerm extractEntry test/isbignum.js
65 silly gunzTarPerm extractEntry test/seed.js
66 silly gunzTarPerm extractEntry test/wincrash.js
67 verbose write writing to /usr/home/nmadmin/node_modules/bignum/package.json
68 info preinstall bignum@0.10.2
69 verbose readDependencies loading dependencies from /usr/home/nmadmin/node_modules/bignum/package.json
70 silly prepareForInstallMany adding nan@~1.8.4 from bignum dependencies
71 verbose readDependencies loading dependencies from /usr/home/nmadmin/node_modules/bignum/package.json
72 silly cache add args [ 'nan@~1.8.4', null ]
73 verbose cache add spec nan@~1.8.4
74 silly cache add parsed spec { raw: 'nan@~1.8.4',
74 silly cache add   scope: null,
74 silly cache add   name: 'nan',
74 silly cache add   rawSpec: '~1.8.4',
74 silly cache add   spec: '>=1.8.4 <1.9.0',
74 silly cache add   type: 'range' }
75 silly addNamed nan@>=1.8.4 <1.9.0
76 verbose addNamed ">=1.8.4 <1.9.0" is a valid semver range for nan
77 silly addNameRange { name: 'nan', range: '>=1.8.4 <1.9.0', hasData: false }
78 silly mapToRegistry name nan
79 silly mapToRegistry using default registry
80 silly mapToRegistry registry https://registry.npmjs.org/
81 silly mapToRegistry uri https://registry.npmjs.org/nan
82 verbose addNameRange registry:https://registry.npmjs.org/nan not in flight; fetching
83 verbose request uri https://registry.npmjs.org/nan
84 verbose request no auth needed
85 info attempt registry request try #1 at 18:07:56
86 verbose etag "9T2TEINHQE1CYR42PWQNCEY3X"
87 http request GET https://registry.npmjs.org/nan
88 http 304 https://registry.npmjs.org/nan
89 silly get cb [ 304,
89 silly get   { date: 'Mon, 20 Jul 2015 18:09:10 GMT',
89 silly get     via: '1.1 varnish',
89 silly get     'cache-control': 'max-age=60',
89 silly get     etag: '"9T2TEINHQE1CYR42PWQNCEY3X"',
89 silly get     age: '36',
89 silly get     connection: 'keep-alive',
89 silly get     'x-served-by': 'cache-dfw1828-DFW',
89 silly get     'x-cache': 'HIT',
89 silly get     'x-cache-hits': '3',
89 silly get     'x-timer': 'S1437415750.813172,VS0,VE0',
89 silly get     vary: 'Accept' } ]
90 verbose etag https://registry.npmjs.org/nan from cache
91 verbose get saving nan to /home/nmadmin/.npm/registry.npmjs.org/nan/.cache.json
92 silly addNameRange number 2 { name: 'nan', range: '>=1.8.4 <1.9.0', hasData: true }
93 silly addNameRange versions [ 'nan',
93 silly addNameRange   [ '0.3.0-wip',
93 silly addNameRange     '0.3.0-wip2',
93 silly addNameRange     '0.3.0',
93 silly addNameRange     '0.3.1',
93 silly addNameRange     '0.3.2',
93 silly addNameRange     '0.4.0',
93 silly addNameRange     '0.4.1',
93 silly addNameRange     '0.4.2',
93 silly addNameRange     '0.4.3',
93 silly addNameRange     '0.4.4',
93 silly addNameRange     '0.5.0',
93 silly addNameRange     '0.5.1',
93 silly addNameRange     '0.5.2',
93 silly addNameRange     '0.6.0',
93 silly addNameRange     '0.7.0',
93 silly addNameRange     '0.7.1',
93 silly addNameRange     '0.8.0',
93 silly addNameRange     '1.0.0',
93 silly addNameRange     '1.1.0',
93 silly addNameRange     '1.1.1',
93 silly addNameRange     '1.1.2',
93 silly addNameRange     '1.2.0',
93 silly addNameRange     '1.3.0',
93 silly addNameRange     '1.4.0',
93 silly addNameRange     '1.4.1',
93 silly addNameRange     '1.5.0',
93 silly addNameRange     '1.4.2',
93 silly addNameRange     '1.4.3',
93 silly addNameRange     '1.5.1',
93 silly addNameRange     '1.5.2',
93 silly addNameRange     '1.6.0',
93 silly addNameRange     '1.5.3',
93 silly addNameRange     '1.6.1',
93 silly addNameRange     '1.6.2',
93 silly addNameRange     '1.7.0',
93 silly addNameRange     '1.8.0',
93 silly addNameRange     '1.8.1',
93 silly addNameRange     '1.8.2',
93 silly addNameRange     '1.8.3',
93 silly addNameRange     '1.8.4' ] ]
94 silly addNamed nan@1.8.4
95 verbose addNamed "1.8.4" is a plain semver version for nan
96 silly cache afterAdd nan@1.8.4
97 verbose afterAdd /home/nmadmin/.npm/nan/1.8.4/package/package.json not in flight; writing
98 verbose afterAdd /home/nmadmin/.npm/nan/1.8.4/package/package.json written
99 silly install resolved [ { name: 'nan',
99 silly install resolved     version: '1.8.4',
99 silly install resolved     description: 'Native Abstractions for Node.js: C++ header for Node 0.8->0.12 compatibility',
99 silly install resolved     main: 'include_dirs.js',
99 silly install resolved     repository: { type: 'git', url: 'git://github.com/iojs/nan.git' },
99 silly install resolved     scripts:
99 silly install resolved      { test: 'tap --gc test/js/*-test.js',
99 silly install resolved        'rebuild-tests': 'pangyp rebuild --directory test' },
99 silly install resolved     contributors:
99 silly install resolved      [ [Object],
99 silly install resolved        [Object],
99 silly install resolved        [Object],
99 silly install resolved        [Object],
99 silly install resolved        [Object],
99 silly install resolved        [Object],
99 silly install resolved        [Object] ],
99 silly install resolved     devDependencies:
99 silly install resolved      { bindings: '~1.2.1',
99 silly install resolved        'node-gyp': '~1.0.2',
99 silly install resolved        pangyp: '~2.0.1',
99 silly install resolved        tap: '~0.7.1',
99 silly install resolved        xtend: '~4.0.0' },
99 silly install resolved     license: 'MIT',
99 silly install resolved     gitHead: 'ed3bbf4ced0cf7937b4e4164766797f71aa97f3d',
99 silly install resolved     bugs: { url: 'https://github.com/iojs/nan/issues' },
99 silly install resolved     homepage: 'https://github.com/iojs/nan#readme',
99 silly install resolved     _id: 'nan@1.8.4',
99 silly install resolved     _shasum: '3c76b5382eab33e44b758d2813ca9d92e9342f34',
99 silly install resolved     _from: 'nan@>=1.8.4 <1.9.0',
99 silly install resolved     _npmVersion: '2.8.3',
99 silly install resolved     _nodeVersion: '0.12.2',
99 silly install resolved     _npmUser: { name: 'kkoopa', email: 'bbyholm@abo.fi' },
99 silly install resolved     maintainers: [ [Object], [Object] ],
99 silly install resolved     dist:
99 silly install resolved      { shasum: '3c76b5382eab33e44b758d2813ca9d92e9342f34',
99 silly install resolved        tarball: 'http://registry.npmjs.org/nan/-/nan-1.8.4.tgz' },
99 silly install resolved     directories: {},
99 silly install resolved     _resolved: 'https://registry.npmjs.org/nan/-/nan-1.8.4.tgz',
99 silly install resolved     readme: 'ERROR: No README data found!' } ]
100 info install nan@1.8.4 into /usr/home/nmadmin/node_modules/bignum
101 info installOne nan@1.8.4
102 verbose installOne of nan to /usr/home/nmadmin/node_modules/bignum not in flight; installing
103 verbose lock using /home/nmadmin/.npm/_locks/nan-d8cc309cc959fff2.lock for /usr/home/nmadmin/node_modules/bignum/node_modules/nan
104 silly install write writing nan 1.8.4 to /usr/home/nmadmin/node_modules/bignum/node_modules/nan
105 verbose unbuild node_modules/bignum/node_modules/nan
106 silly gentlyRm /usr/home/nmadmin/node_modules/bignum/node_modules/nan is being purged from base /usr/home/nmadmin
107 verbose gentlyRm don't care about contents; nuking /usr/home/nmadmin/node_modules/bignum/node_modules/nan
108 verbose tar unpack /home/nmadmin/.npm/nan/1.8.4/package.tgz
109 verbose tar unpacking to /usr/home/nmadmin/node_modules/bignum/node_modules/nan
110 silly gentlyRm /usr/home/nmadmin/node_modules/bignum/node_modules/nan is being purged
111 verbose gentlyRm don't care about contents; nuking /usr/home/nmadmin/node_modules/bignum/node_modules/nan
112 silly gunzTarPerm modes [ '755', '644' ]
113 silly gunzTarPerm extractEntry package.json
114 silly gunzTarPerm modified mode [ 'package.json', 436, 420 ]
115 silly gunzTarPerm extractEntry README.md
116 silly gunzTarPerm modified mode [ 'README.md', 436, 420 ]
117 silly gunzTarPerm extractEntry include_dirs.js
118 silly gunzTarPerm modified mode [ 'include_dirs.js', 436, 420 ]
119 silly gunzTarPerm extractEntry LICENSE.md
120 silly gunzTarPerm modified mode [ 'LICENSE.md', 436, 420 ]
121 silly gunzTarPerm extractEntry .dntrc
122 silly gunzTarPerm modified mode [ '.dntrc', 436, 420 ]
123 silly gunzTarPerm extractEntry appveyor.yml
124 silly gunzTarPerm modified mode [ 'appveyor.yml', 436, 420 ]
125 silly gunzTarPerm extractEntry nan.h
126 silly gunzTarPerm modified mode [ 'nan.h', 436, 420 ]
127 silly gunzTarPerm extractEntry nan_implementation_12_inl.h
128 silly gunzTarPerm modified mode [ 'nan_implementation_12_inl.h', 436, 420 ]
129 silly gunzTarPerm extractEntry nan_implementation_pre_12_inl.h
130 silly gunzTarPerm modified mode [ 'nan_implementation_pre_12_inl.h', 436, 420 ]
131 silly gunzTarPerm extractEntry nan_new.h
132 silly gunzTarPerm modified mode [ 'nan_new.h', 436, 420 ]
133 silly gunzTarPerm extractEntry nan_string_bytes.h
134 silly gunzTarPerm modified mode [ 'nan_string_bytes.h', 436, 420 ]
135 silly gunzTarPerm extractEntry CHANGELOG.md
136 silly gunzTarPerm modified mode [ 'CHANGELOG.md', 436, 420 ]
137 verbose write writing to /usr/home/nmadmin/node_modules/bignum/node_modules/nan/package.json
138 info preinstall nan@1.8.4
139 verbose readDependencies loading dependencies from /usr/home/nmadmin/node_modules/bignum/node_modules/nan/package.json
140 verbose readDependencies loading dependencies from /usr/home/nmadmin/node_modules/bignum/node_modules/nan/package.json
141 silly install resolved []
142 verbose about to build /usr/home/nmadmin/node_modules/bignum/node_modules/nan
143 info build /usr/home/nmadmin/node_modules/bignum/node_modules/nan
144 info linkStuff nan@1.8.4
145 silly linkStuff nan@1.8.4 has /usr/home/nmadmin/node_modules/bignum/node_modules as its parent node_modules
146 verbose linkBins nan@1.8.4
147 verbose rebuildBundles nan@1.8.4
148 info install nan@1.8.4
149 info postinstall nan@1.8.4
150 verbose unlock done using /home/nmadmin/.npm/_locks/nan-d8cc309cc959fff2.lock for /usr/home/nmadmin/node_modules/bignum/node_modules/nan
151 verbose about to build /usr/home/nmadmin/node_modules/bignum
152 info build /usr/home/nmadmin/node_modules/bignum
153 info linkStuff bignum@0.10.2
154 silly linkStuff bignum@0.10.2 has /usr/home/nmadmin/node_modules as its parent node_modules
155 verbose linkBins bignum@0.10.2
156 verbose rebuildBundles bignum@0.10.2
157 verbose rebuildBundles [ 'nan' ]
158 info install bignum@0.10.2
159 verbose unsafe-perm in lifecycle true
160 info bignum@0.10.2 Failed to exec install script
161 verbose unlock done using /home/nmadmin/.npm/_locks/bignum-c76c7b87b91b2968.lock for /usr/home/nmadmin/node_modules/bignum
162 verbose stack Error: bignum@0.10.2 install: `node-gyp configure build`
162 verbose stack Exit status 1
162 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
162 verbose stack     at EventEmitter.emit (events.js:110:17)
162 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
162 verbose stack     at ChildProcess.emit (events.js:110:17)
162 verbose stack     at maybeClose (child_process.js:1015:16)
162 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
163 verbose pkgid bignum@0.10.2
164 verbose cwd /usr/home/nmadmin
165 error FreeBSD 10.0-RELEASE-p7
166 error argv "node" "/usr/local/bin/npm" "install" "bignum@latest"
167 error node v0.12.7
168 error npm  v2.12.1
169 error code ELIFECYCLE
170 error bignum@0.10.2 install: `node-gyp configure build`
170 error Exit status 1
171 error Failed at the bignum@0.10.2 install script 'node-gyp configure build'.
171 error This is most likely a problem with the bignum package,
171 error not with npm itself.
171 error Tell the author that this fails on your system:
171 error     node-gyp configure build
171 error You can get their info via:
171 error     npm owner ls bignum
171 error There is likely additional logging output above.
172 verbose exit [ 1, true ]
173 verbose unbuild node_modules/bignum
174 info preuninstall bignum@0.10.2
175 info uninstall bignum@0.10.2
176 verbose unbuild rmStuff bignum@0.10.2 from /usr/home/nmadmin/node_modules
177 info postuninstall bignum@0.10.2
178 silly gentlyRm /usr/home/nmadmin/node_modules/bignum is being purged from base /usr/home/nmadmin
179 verbose gentlyRm don't care about contents; nuking /usr/home/nmadmin/node_modules/bignum
180 silly vacuum-fs purging /usr/home/nmadmin/node_modules/bignum
181 silly vacuum-fs quitting because other entries in /usr/home/nmadmin/node_modules

**Comment by rvagg** [comment]
so much log, so little help!

Would you mind cloning the repository on that machine and running `npm install` and see what output you get from that? Is it possible you don't have a build toolchain installed?
