### ISSUE TITLE
bignum.node: undefined symbol: node_module_register

### ISSUE THREAD

**Issue by djspacedevil** [justmoon/node-bignum#73]
Did anybody know, how can i fix that problem?

On CentOS
```
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /opt/Pools/unomp/node_modules/bignum/build/Release/bignum.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at new require (module.js:380:17)
    at Object.<anonymous> (/opt/Pools/unomp/node_modules/bignum/index.js:4:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

```

**Comment by rvagg** [comment]
You probably need to rebuild your native addons, `npm rebuild` or just remove your `node_modules` and recompile. Failing to register a native addon _usually_ means that you haven't got a binary that's compatible with the current version of Node.js, perhaps you upgraded from v0.12 to v4 or something.

**Comment by shopglobal** [comment]
nvm use 4 
replace 4 with your intended version of node
then npm rebuild && npm install

As long as you have selected the correct version of node, that goes along with your source.
