### ISSUE TITLE
bignum fails to install on npm 3.10.3

### ISSUE THREAD

**Issue by IComplainInComments** [justmoon/node-bignum#83]
Hello,

Ever since npm 3.10.3/2, I have been unable to build or install bignum on armv7 arch linux. The error I receive is this.

`node-pre-gyp ERR! Tried to download: https://rvagg-node.s3-us-west-2.amazonaws.com/bignum/v0.12.5/bignum-v0.12.5-node-v48-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bignum@0.12.5 and node@6.2.2 (node-v48 ABI) (falling back to source compile with node-gyp) `

It then proceeds to fail to build from source.

The original package I was trying to install was home bridge, and other uses have also had issues attempting to install this package as well, on different platforms/architectures.

Please see here: https://github.com/nfarina/homebridge/issues/694

**Comment by NiackBuster** [comment]
Hello, idem for this version : https://rvagg-node.s3-us-west-2.amazonaws.com/bignum/v0.12.5/bignum-v0.12.5-node-v47-win32-ia32.tar.gz
(For NPM 3.3.6)

**Comment by fabiobortolin** [comment]
Same error for me..

https://rvagg-node.s3-us-west-2.amazonaws.com/bignum/v0.12.5/bignum-v0.12.5-node-v47-win32-ia32.tar.gz

(npm ERR! node v5.0.0
npm ERR! npm v3.3.6)

**Comment by rvagg** [comment]
Note that those "errors" are simply informative, note that it says "falling back to source compile with node-gyp", do you have errors from further down in your install?

@IComplainInComments sorry but v48 for arm wasn't uploaded for some reason, I'm not sure what went wrong but it should be there now if you try again.

@NiackBuster and @fabiobortolin yours are failing because I don't have Windows binaries precompiled yet, they are a bit harder to automate than the others. You'll need to install Visual Studio and Python to get it all happily compiling for you at the moment. See https://github.com/nodejs/node-gyp for details on how to get set up for this.

**Comment by snipem** [comment]
Sorry to warm this up. The fallback doesn't work either. Here is what I get when trying to install it with a checkout from this repository:

```
make: Entering directory '/usr/lib/node_modules/bignum/build'
make: *** No rule to make target '../.node-gyp/6.2.2/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/usr/lib/node_modules/bignum/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.2.3-1-ARCH
```

**Context**

```
matze@beatle:~/build/node-bignum $ git log | head
commit 312837fa6506ff0a34a2136169c302d6b857d1f8
Author: Rod Vagg <rod@vagg.org>
Date:   Thu Jun 16 21:23:38 2016 +1000

    add --timeout 120 to tap

commit 6511d9532f6cab4366ca8116721ee7d048a4b003
Author: Rod Vagg <rod@vagg.org>
Date:   Thu Jun 16 21:03:57 2016 +1000
```
Trying to build it locally:
```
matze@beatle:~/build/node-bignum $ sudo npm -g install
(node:12999) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

> bignum@0.12.5 install /usr/lib/node_modules/bignum
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://rvagg-node.s3-us-west-2.amazonaws.com/bignum/v0.12.5/bignum-v0.12.5-node-v48-linux-ia32.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bignum@0.12.5 and node@6.2.2 (node-v48 ABI) (falling back to source compile with node-gyp)
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.2.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/bignum/.node-gyp"
make: Entering directory '/usr/lib/node_modules/bignum/build'
make: *** No rule to make target '../.node-gyp/6.2.2/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/usr/lib/node_modules/bignum/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.2.3-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/lib/node_modules/bignum/binding/bignum.node" "--module_name=bignum" "--module_path=/usr/lib/node_modules/bignum/binding"
gyp ERR! cwd /usr/lib/node_modules/bignum
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/bignum/binding/bignum.node --module_name=bignum --module_path=/usr/lib/node_modules/bignum/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/bignum/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:852:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Linux 4.2.3-1-ARCH
node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/bignum/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/bignum
node-pre-gyp ERR! node -v v6.2.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.29
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/bignum/binding/bignum.node --module_name=bignum --module_path=/usr/lib/node_modules/bignum/binding' (1)
npm ERR! Linux 4.2.3-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "-g" "install"
npm ERR! node v6.2.2
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE

npm ERR! bignum@0.12.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bignum@0.12.5 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bignum package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bignum
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bignum
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/matze/build/node-bignum/npm-debug.log
```

**Comment by rvagg** [comment]
you're running as root, try and run it as a non-privileged user and see if it makes a difference

**Comment by snipem** [comment]
That won't work, because my user can't write to /usr/lib. But here is the output anyway:

```
npm ERR! Linux 4.2.3-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "-g" "install"
npm ERR! node v6.2.2
npm ERR! npm  v3.5.3
npm ERR! path /usr/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
```

**Comment by rvagg** [comment]
What are you expecting to happen when you run `sudo npm -g install`? you have bignum at /usr/lib/node_modules/, are you intending to have it installed there? Perhaps just completely remove it and start whatever you were doing from scratch `sudo rm -rf /usr/lib/node_modules/bignum/`. There's really no good reason to have a package like bignum installed in your global node_modules, the only things that really should go there are system-wide utilities written in Node, like npm.

**Comment by snipem** [comment]
Projects as [homebridge](https://github.com/nfarina/homebridge) use it as part of their global installation ```sudo npm install -g homebridge```. Their installation is currently broken since it's relying on the global installation feature of bignum.

Edit: The installation of homebridge runs for me now. I can't determine what the fix was as for now. Anyway:

But for me it looks like, that the error is mainly originated in ```https://rvagg-node.s3-us-west-2.amazonaws.com/bignum/v0.12.5/bignum-v0.12.5-node-v47-win32-ia32.tar.gz```resulting in a 403. Could you fix the url or file on that location?

**Comment by rvagg** [comment]
No, there is no Windows binary available, the 403/404 is intentional because it doesn't exist but it will fallback to compiling from source in that case as bignum has always done, you need Visual Studio and Python 2.x installed for this to work.
