### ISSUE TITLE
Installation fails on Windows with upcoming OpenSSL release

### ISSUE THREAD

**Issue by timmywil** [justmoon/node-bignum#85]
I don't expect you to make changes immediately, but I needed to tell someone my experience. I'm on Windows 10 64-bit and I've been working 2 days to get bignum to install (actually, I've been working to install a package that has bignum as a dependency). I followed the directions from Microsoft on installing Visual Studio and python [here](https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#compiling-native-addon-modules)-I tried both options, but stuck with Option 2 so I could use python 64-bit. That fixed the first few errors. Then I installed OpenSSL, but the error I've pasted at the bottom would not go away.

In the upcoming OpenSSL release (1.1.0), it seems the location of a necessary file has been either renamed, moved, or removed entirely. This is not a problem right now because the current LTS version of OpenSSL (1.0.2) still works. Once I downgraded to 1.0.2, bignum finally installed.

This *might* be a big issue given that old OpenSSL versions immediately become unavailable for download due to security vulnerabilities fixed in the latest version. Once version 1.1.0 becomes LTS, I suspect **a lot** of packages are going to have problems.

The important bit is
```
LINK : fatal error LNK1181: cannot open input file 'C:\OpenSSL-Win64\lib\libeay32.lib'
```

```
> bignum@0.12.5 install C:\Users\shear\Code\opentable\start-page-nodejs\node_modules\bignum
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://rvagg-node.s3-us-west-2.amazonaws.com/bignum/v0.12.5/bignum-v0.12.5-node-v46-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bignum@0.12.5 and node@4.4.4 (node-v46 ABI) (falling back to source compile with node-gyp)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  bignum.cc
  win_delay_load_hook.cc
..\bignum.cc(413): warning C4244: '=': conversion from 'double' to 'uint64_t', possible loss of data [C:\Users\shear\Co
de\opentable\start-page-nodejs\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(810): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data [C:\Users\shear\Code\op
entable\start-page-nodejs\node_modules\bignum\build\bignum.vcxproj]
..\bignum.cc(825): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data [C:\Users\shear\Code\op
entable\start-page-nodejs\node_modules\bignum\build\bignum.vcxproj]
LINK : fatal error LNK1181: cannot open input file 'C:\OpenSSL-Win64\lib\libeay32.lib' [C:\Users\shear\Code\opentable\s
tart-page-nodejs\node_modules\bignum\build\bignum.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\shear\Code\opentable\start-page-nodejs\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\shear\\Code\\opentable\\start-page-nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\shear\\Code\\opentable\\start-page-nodejs\\node_modules\\bignum\\binding\\bignum.node" "--module_name=bignum" "--module_path=C:\\Users\\shear\\Code\\opentable\\start-page-nodejs\\node_modules\\bignum\\binding"
gyp ERR! cwd C:\Users\shear\Code\opentable\start-page-nodejs\node_modules\bignum
gyp ERR! node -v v4.4.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\shear\Code\opentable\start-page-nodejs\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\shear\Code\opentable\start-page-nodejs\node_modules\bignum\binding\bignum.node --module_name=bignum --module_path=C:\Users\shear\Code\opentable\start-page-nodejs\node_modules\bignum\binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\shear\Code\opentable\start-page-nodejs\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\shear\\Code\\opentable\\start-page-nodejs\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\shear\Code\opentable\start-page-nodejs\node_modules\bignum
node-pre-gyp ERR! node -v v4.4.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\shear\Code\opentable\start-page-nodejs\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\shear\Code\opentable\start-page-nodejs\node_modules\bignum\binding\bignum.node --module_name=bignum --module_path=C:\Users\shear\Code\opentable\start-page-nodejs\node_modules\bignum\binding' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN browserify-shim@3.8.12 requires a peer of browserify@>= 2.3.0 < 14 but none was installed.
npm WARN grunt-promote-build@0.1.3 requires a peer of grunt-shell@>0.6.0 but none was installed.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "bignum@latest"
npm ERR! node v4.4.4
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! bignum@0.12.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bignum@0.12.5 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bignum package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bignum
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bignum
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\shear\Code\opentable\start-page-nodejs\npm-debug.log
```

**Comment by dartess** [comment]
damn i got here late 2021

**Comment by unruledboy** [comment]
5 years later, still no solution
